### ISSUE TITLE
Recommend purging actual/expected values of assertions

### ISSUE THREAD

**Issue by trentmwillis** [js-reporters/js-reporters#100]
The current spec states that Assertion data should contain the actual/expected values as properties. This is good for reporting, but also prone to memory leaks. By holding onto references for values that are non-primitive, we leak memory over the life of a test suite since Tests hold onto an array of Assertions.

Thus, I think we should recommend that actual/expected values of assertions get "purged" (deleted) from Assertion objects once the corresponding Test has finished executing. I can't think of a good reason to hold on to that information throughout the entire test suite and it will reduce the potential for leaking memory.

**Comment by Krinkle** [comment]
This was removed in dce64599d541, as I wasn't sure whether it still applies. I'm re-opening to make sure the issue is well-understood and dealt as part of the RFC at https://github.com/js-reporters/js-reporters/issues/117.

Two alternative ideas:

* Remove `assertions` from the TestEnd event data. Perhaps introduce an optional `assertion` event instead. This would mean testing frameworks can let go of it after emitting this event. It is then up to reporters to decide whether to listen. If they do, the reporter will be the sole reference holder has control over its allocation.
* Or, keep `assertions` on TestEnd but instead remove `tests` from SuiteEnd.

Either of these would effectively set a direction where, to obtain information about an event, the reporter has to listen to it. We would not require testing frameworks to hold on and build up large object structures over an entire test run. I think this direction is viable, so long as we're absoolutely sure that it isn't cutting off any use cases.

I think building up a large object is a legit use case, and would actually make for a really good demonstration of the CRI standard. We could even ship a helper method that does this for you, e.g. by registering a reporter and returning a Promise that resolves to the large object after `runEnd` is emitted. Whilst by default allowing runners to be more stream-like and memory-friendly.

Thoughts?

**Comment by Krinkle** [comment]
Superseded by https://github.com/js-reporters/js-reporters/issues/126.
