### ISSUE TITLE
Standard API

### ISSUE THREAD

**Issue by JamesMGreene** [js-reporters/js-reporters#3]
In this issue thread, I would like to focus on standardizing the Reporter API/interface so that we could hopefully share Reporter plugins between testing frameworks.

This would most likely come in the form of:
- an EventEmitter interface (`.on(...)`/`.off(...)`) _**OR**_ an object with particular property names (e.g. `runStarted`/`onRunStart`/etc.)
- particular events/properties that would handle configuration of the Reporter itself when it is registered/unregistered with the test framework, e.g. `start` and `stop` in [Intern's Custom Reporter API](https://github.com/theintern/intern/wiki/Using-and-Writing-Reporters#custom-reporters)
- _maybe_ a standard-ish way to register a Reporter, e.g. `MyLib.addReporter(x)`, `MyLib.reporter = x;`, etc.

---

Depends on:
- [x] #1: Which events to include in the standard
- [x] #4: How to indicate status of a test

**Comment by flore77** [comment]
There is one more thing that I want to settle in this issue, which is:

> maybe a standard-ish way to register a Reporter

then I think it can be closed.

Since we have adopted the standard with the EventEmitter interface, I think there should be a method, which can add an infinite number of reporters:

```js
testFramework.addReporter(reporter);
```

and there should be also a method in which we set the default reporter (better said overwrite it):

```js
testFramework.setDefaultReporter(reporter);
```

I am thinking if it would be good to have also a second param called `options`:

```js
testFramework.addReporter(reporter, options);
```

so that reporters can be customized by receiving different options. I know Mocha has this feature.

What do you think about it?

/cc @boneskull @searls

**Comment by flore77** [comment]
>  Is that passed to a constructor, implying the reporter argument to be the constructor

Yes.

**Comment by jzaefferer** [comment]
Okay, sounds good to me.

**Comment by flore77** [comment]
@boneskull are you ok with this ?
