### ISSUE TITLE
testEnd property for all assertions

### ISSUE THREAD

**Issue by jzaefferer** [js-reporters/js-reporters#31]
QUnit reports all assertions, passing or failing: http://api.qunitjs.com/QUnit.log/

There's no need for all frameworks to provide that, but it would make sense to have an array of assertions on the testEnd event. QUnit could make use of that, other frameworks could just leave it null/undefined, reporters can then see if its there and skip it if not.

**Comment by jzaefferer** [comment]
To clarify, while `testEnd.errors` provides a list of failed assertions, it ignores/skips passing assertions. To rebuild QUnit's HTML reporter on top of js-reporters, we'd have to provide both.

**Comment by flore77** [comment]
Now it is clearer. I see 2 solutions here, we can introduce a new event in the standard something like `assertion done`, or even 2 events `assertion failed` and `assertion passed`, or we can only add a new prop to the `Test` object, like `Test.assertions` type `{Array}`.

And yes, it would be really hard for all frameworks to provide this, for example `Mocha` generates something like this on `test.err` prop, but only for failed assertions (I guess the props of `test.err` depend on the used assertion library, since Mocha does not have built in assertions), as also only for the last failed assertion in a test, so if you have multiple assertions within a test that are failing you would get only the first one.

I think this issue must wait for for #30 as also for a full review of the standard, and then we would update the QUnit adapter, as also the others adapters, accordingly.

**Comment by jzaefferer** [comment]
Waiting for #30 makes sense. We can get back to this, then.

One note about event naming - the draft spec has some details on [how the names were picked](https://github.com/js-reporters/js-reporters#selection-criteria), this is relevant to your suggestions: "It uses names that are valid JavaScript identifiers, which allows using those as keys in JSON and avoids the need to quote keys in regular JS objects or function calls."

**Comment by flore77** [comment]
Indeed, it is a good criterion :+1:

**Comment by flore77** [comment]
@jzaefferer we can do this now.

* Qunit - can provide this through his [log callback](http://api.qunitjs.com/QUnit.log/)
* Jasmine - can provide this through its `failedExpectations` and `passedExpectations` props available through the `specDone` callback
* Mocha - cannot provide this

I think the best solution for this would be to to put a new property on the test object, `test.assertions`. Should this new prop contain also the failed assertions, that are already contained in the  `error` property?

On `testStart` the prop will be undefined.

**Comment by jzaefferer** [comment]
`test.assertions` sounds good to me. Can contain the same failed assertions as `test.errors`.

For Mocha it'll be empty or contain the one error?

**Comment by flore77** [comment]
> For Mocha it'll be empty or contain the one error?

I don't know.  I guess it would be better if it'll be empty, because it wouldn't reflect the true meaning of the prop, assertions.

> Can contain the same failed assertions as test.errors.

Yes, I think this prop can contain the native assertions emitted by each framework and `test.errors` would contain a normalized error.

**Comment by jzaefferer** [comment]
Okay, let's start with that. Could still try to normalize `test.assertions` later.

**Comment by flore77** [comment]
> Could still try to normalize test.assertions later.

Hmm, and then should it be good to have also `assertions` as also `errors` ?

If we provide `normalized assertions`, something like:

```js
var assertion = {
  type: failed || passed,
  ...
};
```

It would be trivial to get `errors` out of this with a simple filter, `assertions.filter(assertion => assertion.type === 'failed')`.

**Comment by jzaefferer** [comment]
Are you suggesting `test.errors` wouldn't be necessary? I wouldn't go there.

**Comment by flore77** [comment]
> Are you suggesting test.errors wouldn't be necessary? 

Hmm, I was only thinking to not have duplicate data. But because this property is optional, I think it wouldn't be such a big deal.

I will begin the implementation and we'll see how it comes out.
